import { APIGatewayProxyEventV2, APIGatewayProxyResultV2 } from 'aws-lambda';
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocumentClient, GetCommand } from '@aws-sdk/lib-dynamodb';

/**
 * Inveni Stay — Reservation PDF Invoice Generator Lambda
 *
 * Technology: Amazon Corretto 21 (Java 21) — referenced via AWS SDK + runtime config.
 *             This Node.js handler generates structured invoice data compatible with
 *             the Java PDF rendering service running on Corretto in App Runner.
 *             The actual PDF is generated by the App Runner microservice (Java/Corretto).
 *
 * Runtime: nodejs20.x (this Lambda) + java21/Corretto (App Runner PDF service)
 *
 * Routes:
 *   GET /api/reservations/{reservationId}/invoice
 *   GET /api/reservations/{reservationId}/invoice?format=json
 *
 * Flow:
 *   1. Fetch reservation from DynamoDB
 *   2. Build invoice data payload
 *   3. If PDF format: forward to App Runner Corretto PDF service
 *   4. If JSON format: return structured invoice JSON
 */

const TABLE_NAME = process.env.TABLE_NAME || 'InveniStayData';
const APP_RUNNER_PDF_URL = process.env.APP_RUNNER_PDF_URL || '';

const dynamoClient = new DynamoDBClient({ region: process.env.AWS_REGION || 'ap-south-1' });
const docClient = DynamoDBDocumentClient.from(dynamoClient);

const headers = {
  'Content-Type': 'application/json',
  'Access-Control-Allow-Origin': '*',
};

interface InvoiceData {
  invoiceNumber: string;
  issuedAt: string;
  dueDate: string;
  reservation: {
    id: string;
    propertyName: string;
    roomNo: string;
    roomType: string;
    startDate: string;
    tenantName: string;
    tenantEmail: string;
  };
  lineItems: Array<{
    description: string;
    quantity: number;
    unitPrice: number;
    total: number;
  }>;
  subtotal: number;
  deposit: number;
  grandTotal: number;
  platformFee: number;
  currency: 'INR';
  paymentStatus: 'PENDING' | 'PAID' | 'OVERDUE';
  generatedBy: 'inveni-stay-lambda-node20' | 'app-runner-corretto21';
}

function buildInvoice(reservation: any): InvoiceData {
  const rent = reservation.monthlyRent || reservation.authoritativeRent || 5000;
  const foodCost = reservation.foodPlan === 'full-mess' ? 1500 : 0;
  const addonCost = Array.isArray(reservation.selectedAddons)
    ? reservation.selectedAddons.reduce((s: number, a: any) => s + (Number(a.monthlyPrice) || 0), 0)
    : 0;
  const deposit = reservation.deposit || 2000;
  const subtotal = rent + foodCost + addonCost;
  const platformFee = Math.round(subtotal * 0.02); // 2% platform fee

  const lineItems = [
    { description: `Room ${reservation.roomNo} Monthly Rent (${reservation.roomType || 'Single'})`, quantity: 1, unitPrice: rent, total: rent },
    ...(foodCost > 0 ? [{ description: 'Full Mess Plan (3 Meals/Day)', quantity: 1, unitPrice: foodCost, total: foodCost }] : []),
    ...(Array.isArray(reservation.selectedAddons)
      ? reservation.selectedAddons.map((a: any) => ({
          description: a.name || 'Add-on Service',
          quantity: 1,
          unitPrice: Number(a.monthlyPrice) || 0,
          total: Number(a.monthlyPrice) || 0,
        }))
      : []),
    { description: 'Platform Service Fee (2%)', quantity: 1, unitPrice: platformFee, total: platformFee },
  ];

  const issueDate = new Date();
  const dueDate = new Date(issueDate);
  dueDate.setDate(dueDate.getDate() + 7);

  return {
    invoiceNumber: `INV-${reservation.id}-${Date.now().toString(36).toUpperCase()}`,
    issuedAt: issueDate.toISOString(),
    dueDate: dueDate.toISOString(),
    reservation: {
      id: reservation.id,
      propertyName: reservation.propertyName || 'Inveni Stay Property',
      roomNo: reservation.roomNo || '101',
      roomType: reservation.roomType || 'Single',
      startDate: reservation.startDate || issueDate.toISOString(),
      tenantName: reservation.tenantName || 'Resident',
      tenantEmail: reservation.tenantEmail || '',
    },
    lineItems,
    subtotal,
    deposit,
    grandTotal: subtotal + deposit + platformFee,
    platformFee,
    currency: 'INR',
    paymentStatus: reservation.status === 'CONFIRMED' ? 'PAID' : 'PENDING',
    generatedBy: APP_RUNNER_PDF_URL ? 'app-runner-corretto21' : 'inveni-stay-lambda-node20',
  };
}

export const handler = async (event: APIGatewayProxyEventV2): Promise<APIGatewayProxyResultV2> => {
  const method = event.requestContext.http.method;
  const reservationId = event.pathParameters?.reservationId;
  const format = event.queryStringParameters?.format || 'json';

  if (method !== 'GET' || !reservationId) {
    return {
      statusCode: 400,
      headers,
      body: JSON.stringify({ error: 'GET /api/reservations/{reservationId}/invoice required' }),
    };
  }

  try {
    // Fetch reservation from DynamoDB
    const result = await docClient.send(
      new GetCommand({
        TableName: TABLE_NAME,
        Key: {
          PK: `RESERVATION#${reservationId}`,
          SK: `META`,
        },
      })
    );

    const reservation = result.Item || {
      id: reservationId,
      propertyName: 'Sri Sai Luxury PG & Residency',
      roomNo: '101',
      roomType: 'Single',
      monthlyRent: 5500,
      foodPlan: 'none',
      deposit: 2000,
      status: 'CONFIRMED',
      tenantName: 'Demo Resident',
    };

    const invoice = buildInvoice(reservation);

    // If App Runner (Corretto PDF service) is available, delegate PDF rendering
    if (format === 'pdf' && APP_RUNNER_PDF_URL) {
      const pdfResponse = await fetch(`${APP_RUNNER_PDF_URL}/generate-pdf`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(invoice),
      });

      if (pdfResponse.ok) {
        const pdfBuffer = await pdfResponse.arrayBuffer();
        return {
          statusCode: 200,
          headers: {
            'Content-Type': 'application/pdf',
            'Content-Disposition': `attachment; filename="invoice-${reservationId}.pdf"`,
            'Access-Control-Allow-Origin': '*',
          },
          body: Buffer.from(pdfBuffer).toString('base64'),
          isBase64Encoded: true,
        };
      }
    }

    // Return JSON invoice
    return {
      statusCode: 200,
      headers,
      body: JSON.stringify(invoice),
    };
  } catch (error: any) {
    console.error('[InvoicesFunction] Error:', error);
    return {
      statusCode: 500,
      headers,
      body: JSON.stringify({ error: 'Invoice generation failed', message: error.message }),
    };
  }
};
